/* Run against a development server with the music module initially uninstalled. */
const assert = require('node:assert/strict');
const { chromium } = require('playwright');
const path = require('node:path');
const fs = require('node:fs');

(async () => {
  const base = process.env.MODULE_TEST_URL || 'http://127.0.0.1:8015';
  const out = path.resolve('build/module-ui'); fs.mkdirSync(out, { recursive: true });
  const browser = await chromium.launch({ headless: true, channel: process.env.PLAYWRIGHT_CHANNEL || 'msedge' });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [], requests = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => requests.push(request.url()));
  const screenshot = name => page.screenshot({ path: path.join(out, name), fullPage: true, animations: 'disabled' });
  try {
    await page.goto(base + '/web/index.html#mode', { waitUntil: 'domcontentloaded' });
    await page.locator('#page-mode.active').waitFor();
    const cardOrder = () => page.locator('#mode-secondary > .mode-card').evaluateAll(cards => cards.map(card => card.id));
    assert.deepEqual(await cardOrder(), ['mode-tdcs', 'mode-ssvep', 'mode-mi', 'mode-music']);
    assert.equal(await page.locator('#mode-music.mode-card--uninstalled').count(), 1);
    assert.equal(await page.locator('#page-music').count(), 0);
    assert.equal(requests.some(url => url.includes('/api/music/') || url.includes('/api/modules/music/assets/')), false);
    await screenshot('default.png');
    await page.locator('#mode-scroll-next').hover();
    await page.locator('#mode-scroll-next').click();
    await page.waitForFunction(() => {
      const track = document.getElementById('mode-secondary');
      return track.scrollLeft >= track.scrollWidth - track.clientWidth - 2;
    });
    await screenshot('default-right.png');
    await page.locator('#mode-music').click();
    await page.locator('#module-manager-modal:not([hidden])').waitFor();
    await page.locator('#module-install:not([disabled])').waitFor();
    assert.equal(await page.locator('#module-open, #module-manager-status, #module-manager-refresh').count(), 0);
    assert.equal(await page.locator('.module-catalog-actions > button:visible').count(), 1);
    assert.equal(await page.locator('#module-install.btn--primary:visible').count(), 1);
    assert.equal(await page.locator('#module-uninstall.btn--danger:visible').count(), 0);
    await screenshot('install.png');
    const installUrl = '**/api/modules/music/install';
    await page.route(installUrl, route => route.fulfill({ status: 409, contentType: 'application/json', body: JSON.stringify({ detail: '安装失败，请重试' }) }));
    await page.locator('#module-install').click();
    await page.locator('#module-installed-state').filter({ hasText: '安装失败' }).waitFor();
    await page.waitForFunction(() => !document.getElementById('module-install').disabled);
    assert.equal(await page.locator('#mode-music.mode-card--uninstalled').count(), 1);
    await page.unroute(installUrl);
    let releaseInstall;
    const installGate = new Promise(resolve => { releaseInstall = resolve; });
    await page.route(installUrl, async route => { await installGate; await route.continue(); });
    try {
      await page.locator('#module-install').click();
      await page.locator('#module-install.module-action--busy').waitFor();
      assert.equal(await page.locator('#module-install').isDisabled(), true);
      const transform = await page.locator('#module-install').evaluate(el => getComputedStyle(el, '::before').transform);
      await page.waitForFunction(previous => getComputedStyle(document.getElementById('module-install'), '::before').transform !== previous, transform);
      await screenshot('installing.png');
    } finally { releaseInstall(); }
    await page.locator('#module-uninstall:not([disabled])').waitFor();
    await page.unroute(installUrl);
    assert.equal(await page.locator('.module-catalog-actions > button:visible').count(), 1);
    assert.equal(await page.locator('#module-install:visible').count(), 0);
    assert.equal(await page.locator('#module-uninstall.btn--danger:visible').count(), 1);
    await screenshot('installed-manager.png');
    assert.deepEqual(await cardOrder(), ['mode-tdcs', 'mode-ssvep', 'mode-mi', 'mode-music']);
    await page.locator('#module-manager-close').click();
    await page.locator('#mode-music').click();
    await page.locator('#page-music.active').waitFor();
    await page.waitForFunction(() => document.querySelectorAll('.music-song').length === 10);
    assert.equal(await page.locator('#mode-music').count(), 1);
    assert.equal(await page.locator('#music-start').isDisabled(), true);
    await screenshot('installed-page.png');
    await page.reload({ waitUntil: 'domcontentloaded' });
    await page.locator('#page-music.active').waitFor();
    await page.waitForFunction(() => document.querySelectorAll('.music-song').length === 10);
    await page.goto(base + '/web/index.html#mode');
    await page.locator('#page-mode.active').waitFor();
    await page.locator('#mode-music').waitFor();
    await screenshot('installed-mode.png');
    await page.locator('#theme-toggle').click();
    await page.locator('#btn-module-manager').click();
    await page.locator('#module-uninstall:not([disabled])').waitFor();
    assert.equal(await page.locator('.module-catalog-actions > button:visible').count(), 1);
    assert.equal(await page.locator('#module-uninstall.btn--danger:visible').count(), 1);
    await screenshot('installed-manager-light.png');
    await page.setViewportSize({ width: 390, height: 844 });
    await screenshot('manager-mobile.png');
    const overflow = await page.locator('.module-manager').evaluate(el => el.scrollWidth > el.clientWidth);
    assert.equal(overflow, false, 'Module manager must fit mobile viewport');
    await page.locator('#module-uninstall').click();
    await page.waitForFunction(() => document.querySelector('#mode-music.mode-card--uninstalled') && !document.querySelector('#page-music'));
    assert.deepEqual(await cardOrder(), ['mode-tdcs', 'mode-ssvep', 'mode-mi', 'mode-music']);
    const response = await page.request.get(base + '/api/music/library');
    assert.equal(response.status(), 404);
    await page.goto(base + '/web/index.html#music-export');
    await page.locator('#module-manager-modal:not([hidden])').waitFor();
    await page.locator('#page-mode.active').waitFor();
    assert.equal(await page.locator('#page-music-export').count(), 0);
    assert.deepEqual(errors, []);
    console.log(JSON.stringify({ status: 'passed', screenshots: out, errors }, null, 2));
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
